engines:
  structure:
    enabled: true
  duplication:
    enabled: true
    config:
      debug: true
      languages:
        go:
          mass_threshold: 30
exclude_paths:
- "**/*_test.go"
- config/
- db/
- dist/
- features/
- "**/node_modules/"
- script/
- "**/spec/"
- "**/test/"
- "**/tests/"
- "**/vendor/"
- "**/*.d.ts"
